# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/main/resources/static

stages:
- stage:
  jobs:
    - job:
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            pwd
            cp *.war $(System.DefaultWorkingDirectory)/packer-app-image/ROOT.war
            ls -l
            cd  $(System.DefaultWorkingDirectory)/packer-app-image/
            ls -l
          workingDirectory: '$(System.DefaultWorkingDirectory)/target'
      - task: PackerTool@0
        inputs:
          version: '1.7.8'
      - task: Packer@1
        inputs:
          connectedServiceType: 'azure'
          azureSubscription: 'hyukjun-packer'
          templatePath: '$(System.DefaultWorkingDirectory)/packer-app-image'
          command: 'build'
          variables: |
            file_location=$(System.DefaultWorkingDirectory)/packer-app-image
            managed_image_name=springboot-application-$(Build.BuildNumber)
            managed_image_resource_group_name=rg-packer