source "azure-arm" "autogenerated_1" {
  # 앱정보
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  subscription_id                   = "${var.subscription_id}"
  tenant_id                         = "${var.tenant_id}"

  # 이미지 만들때 사용될 Base Image
  location                          = "${var.location}"
  image_offer                       = "${var.offer}"
  image_publisher                   = "${var.publisher}"
  image_sku                         = "${var.sku}"
  os_type                           = "${var.os_type}"
  vm_size                           = "${var.size}"
  ssh_username = "azureuser"

  # 앞으로 생성될 정보
  managed_image_name                = "${var.managed_image_name}"
  managed_image_resource_group_name = "${var.managed_image_resource_group_name}"
  
  # 태그
  azure_tags = {
    team = "${var.team}"
    worker = "${var.worker}"
    version = "v2.0"
  }
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  # JAVA, TOMCAT 설치
  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline_shebang  = "/bin/sh -x"
    inline          = [
        "apt-get install -y wget",
        "mkdir -p /tmp/lib && cd /tmp/lib",
        "cd /tmp/lib",
        "wget https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz",
        "tar xfz openjdk-15_linux-x64_bin.tar.gz -C /usr/local",
        "wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.59/bin/apache-tomcat-8.5.59.tar.gz",
        "tar xfz apache-tomcat-8.5.59.tar.gz -C /usr/local",
        "cd /usr/local",
        "ln -s apache-tomcat-8.5.59/ tomcat",
        "bash -c 'echo \"JAVA_HOME=/usr/local/jdk-15\" >> /etc/profile'",
        "bash -c 'echo \"JRE_HOME=/usr/local/jdk-15\" >> /etc/profile'",
        "bash -c 'echo \"CATALINA_HOME=/usr/local/tomcat\" >> /etc/profile'",
        "bash -c 'echo \"CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$CATALINA_HOME/lib/jsp-api.jar:$CATALINA_HOME/lib/servlet-api.jar\" >> /etc/profile'",
        "bash -c 'echo \"PATH=$PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin\" >> /etc/profile'",
        "bash -c 'echo \"export JAVA_HOME CLASSPATH PATH CATALINA_HOME JRE_HOME\" >> /etc/profile'",
        "sudo chown -R azureuser:azureuser /usr/local/tomcat/",
        "ls -al /usr/local/tomcat",
        ". /etc/profile",
      ]
  }

  # TOMCAT 서비스 등록
  provisioner "file" {
    source = "${var.file_location}/tomcat.service"
    destination = "~/tomcat.service"
  }

  # TOMCAT 서비스 시작
  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline_shebang  = "/bin/sh -x"
    inline          = [
        "sudo mv /home/azureuser/tomcat.service /etc/systemd/system/",
        "sudo systemctl enable tomcat.service",
        "sudo systemctl start tomcat.service",
      ]
  }

  # TOMCAT appBase에 ROOT.war 배치
  provisioner "file" {
    source = "${var.file_location}/ROOT.war"
    destination = "/usr/local/tomcat/webapps/"
  }

  # 이미지 생성을 위한 Azure VM 에이전트+사용자 삭제
  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline_shebang  = "/bin/sh -x"
    inline          = [
         "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
      ]
  }
}
