# This is a basic workflow to help you get started with Actions

# Workflow
name: Publish Docker image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
    inputs:
      dir:
        description: 'Build Directory'
        required: true
      tag:
        description: 'Image tag'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.HJ_PAT }}
      - name: Push to Github Container Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/namhj94/${{ github.event.inputs.dir }}:${{ github.event.inputs.tag }}
          file: ./${{ github.event.inputs.dir }}/Dockerfile
          context: ./${{ github.event.inputs.dir }}
