# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - none

variables:
  dockerVersion: "20.10.7"
  imageVersion: "2.0"
  repository: "hyukjun/webscrapper"

stages:
  - stage: Build
    displayName: Build and Deploy
    jobs:
      - job:
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: DockerInstaller@0
          displayName: Docker Build and Push
          inputs:
            dockerVersion: $(dockerVersion)
        - task: Docker@2
          displayName: Docker Build and Push
          inputs:
            containerRegistry: 'adoToDockerhub'
            repository: '$(repository)'
            command: 'buildAndPush'
            Dockerfile: 'v2/Dockerfile'
            buildContext: 'v2'
            tags: '$(imageVersion)'